

name: Guardian CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-locked.txt
          pip install -r dev-requirements.txt
          pip install -r test-requirements.txt

      - name: Run Pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run Pytest
        run: |
          pytest --maxfail=2 --disable-warnings --tb=short